#%RAML 0.8
---
title: demo
version: v1

/foo:
  /bar:
    post:
      responses:
        204:
          description: no body needed here
        400:
          description: no body needed here
        500:
          description: no body needed here
